package com.binissa.plugins

import android.content.Context
import com.binissa.core.domain.model.Event
import kotlinx.coroutines.flow.Flow

interface GaugeXPlugin {
    /**
     * Unique identifier for the plugin
     */
    val id: String

    /**
     * Initialize the plugin
     * @param context Application context
     * @param config Configuration for the plugin
     * @return True if initialization was successful
     */
    suspend fun initialize(context: Context, config: Map<String, Any>): Boolean

    /**
     * Start monitoring with this plugin
     */
    suspend fun startMonitoring()

    /**
     * Stop monitoring with this plugin
     */
    suspend fun stopMonitoring()

    /**
     * Get the flow of events generated by this plugin
     */
    fun getEvents(): Flow<Event>

    /**
     * Clean up resources when the plugin is no longer needed
     */
    suspend fun shutdown()
}
